### ISSUE TITLE
Wrong ü-ű associations in Old Hungarian section

### ISSUE THREAD

**Issue by rovasiras** [moebiuscurve/ibus-table-others#30]
The standard based on Sándor Forrai's orthography. By his orthography preferred Nikolsburg UE as Ű

**Comment by mike-fabian** [comment]
Can you explain this in a bit more detail?

**Comment by mike-fabian** [comment]
I think you mean that in cases like the following in https://unicode.org/charts/PDF/U10C80.pdf where there is a conflict:

10CAD 𐲭 OLD HUNGARIAN CAPITAL LETTER RUDIMENTA UE
= Ü, Ű
• used for Ü in Sándor Forrai’s orthography

then we should use what is in Sándor Forrai’s orthography, i.e. typing Ü should produce 𐲭 and typing Ű should produce 𐲬 because of

10CAC 𐲬 OLD HUNGARIAN CAPITAL LETTER
NIKOLSBURG UE
= Ü
• also used for Ö
• used for Ű in Sándor Forrai’s orthography

I.e. it should be just the other way round as it is now.

Is that correct?

**Comment by rovasiras** [comment]
> I think you mean that in cases like the following in https://unicode.org/charts/PDF/U10C80.pdf where there is a conflict:
> 
> 10CAD 𐲭 OLD HUNGARIAN CAPITAL LETTER RUDIMENTA UE = Ü, Ű • used for Ü in Sándor Forrai’s orthography
> 
> then we should use what is in Sándor Forrai’s orthography, i.e. typing Ü should produce 𐲭 and typing Ű should produce 𐲬 because of
> 
> 10CAC 𐲬 OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG UE = Ü • also used for Ö • used for Ű in Sándor Forrai’s orthography
> 
> I.e. it should be just the other way round as it is now.
> 
> Is that correct?

Yes.

**Comment by mike-fabian** [comment]
Good, thank you, I have changed that one.

**Comment by mike-fabian** [comment]
Included in Release 1.3.16: https://github.com/moebiuscurve/ibus-table-others/releases/tag/1.3.16
