### ISSUE TITLE
Missing small and capital symbols from the Old Hungarian table

### ISSUE THREAD

**Issue by rovasiras** [moebiuscurve/ibus-table-others#34]
Missing the following Old Hungarian small and capital symbols: "enc", "and", "ech", "ent shaped sign"

**Comment by mike-fabian** [comment]
For "ent shaped sign" I used “ents” as the typing sequence to keep it short. I hope that is convenient.

**Comment by rovasiras** [comment]
> For "ent shaped sign" I used “ents” as the typing sequence to keep it short. I hope that is convenient.

I think, it would be better, if in this case use the similar method with "aK" symbol (k_), so the form is "ent_".

**Comment by mike-fabian** [comment]
> > For "ent shaped sign" I used “ents” as the typing sequence to keep it short. I hope that is convenient.
> 
> I think, it would be better, if in this case use the similar method with "aK" symbol (k_), so the form is "ent_".

Yes, you are right. On top of that, I think I should move these to the front as prefixes, i.e. `_ent` because it otherwise interferes with typing ‍‍‍‍`e`, `n`, `t` seperately. If two sequences start with the same letter like `e` and `ent_`, then after typing just `en` you see already the result for `ent_` and you cannot get the single result for `e` anymore. You would need to commit by typing arrow right directly after the `e`  (or commit by space and then remove the extra space by Backspace after the `e` is committed). That is very inconvenient. In Chinese input methods, such ambiguity is usually resolved by showing a popup list of candidates and selecting one. But here we don't want it, the result of `ent_` popping up as a choice when just typing `e` would be very disturbing. So I think the special symbols accessed by their name need a prefix, like `_ent`.

Overall I think we need two prefixes, one for accessing special symbols by their name (maybe `_` is good for taht) and another prefix to do what AltGr does on the keyboard layouts.

**Comment by mike-fabian** [comment]
Included in Release 1.3.16: https://github.com/moebiuscurve/ibus-table-others/releases/tag/1.3.16
